### ISSUE TITLE
issue with docker run

### ISSUE THREAD

**Issue by andrewcz** [compops/qnmh-sysid2018#1]
hey mate, cheers for the repository.
getting an error on the docker run.

gcc -pthread -shared build/temp.linux-x86_64-3.6/state/particle_methods/cython_lgss_helper.o -L/usr/local/lib -lpython3.6m -o /app/python/state/particle_methods/cython_lgss_helper.cpython-36m-x86_64-linux-gnu.so
building 'state.particle_methods.cython_sv_helper' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/usr/local/include/python3.6m -c state/particle_methods/cython_sv_helper.c -o build/temp.linux-x86_64-3.6/state/particle_methods/cython_sv_helper.o
gcc -pthread -shared build/temp.linux-x86_64-3.6/state/particle_methods/cython_sv_helper.o -L/usr/local/lib -lpython3.6m -o /app/python/state/particle_methods/cython_sv_helper.cpython-36m-x86_64-linux-gnu.so
  File "run_script.py", line 10
    elif int(sys.argv[1]) == 2:
                              ^
IndentationError: unindent does not match any outer indentation level
  File "run_script.py", line 10
    elif int(sys.argv[1]) == 2:
                              ^
IndentationError: unindent does not match any outer indentation level
  File "run_script.py", line 10
    elif int(sys.argv[1]) == 2:
                              ^
IndentationError: unindent does not match any outer indentation level
tar: Removing leading `/' from member names
tar: /app/results/*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

**Comment by andrewcz** [comment]
v_helper.o
gcc -pthread -shared build/temp.linux-x86_64-3.6/state/particle_methods/cython_sv_helper.o -L/usr/local/lib -lpython3.6m -o /app/python/state/particle_methods/cython_sv_helper.cpython-36m-x86_64-linux-gnu.so
  File "run_script.py", line 10
    elif int(sys.argv[1]) == 2:
                              ^
IndentationError: unindent does not match any outer indentation level
  File "run_script.py", line 10
    elif int(sys.argv[1]) == 2:
                              ^
IndentationError: unindent does not match any outer indentation level
  File "run_script.py", line 10
    elif int(sys.argv[1]) == 2:
                              ^
IndentationError: unindent does not match any outer indentation level
tar: Removing leading `/' from member names
tar: /app/results/*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors


still getting the above 
apologies,
Andrew

**Comment by compops** [comment]
Sorry about these problems. I mixed up the tags on DockerHub. I have rebuild the image and assigned the proper tags to it. I have also changed the run script a bit to allow for running a single experiment. Please, see the new README.md file in the repo for the instructions.
